POST http://localhost:3333/boneca
Content-Type: application/json

{
    "colecao": "Colecao 01",
    "marca": "Marca 01",
    "descricao": "Barbie"
}

###

GET http://localhost:3333/boneca

###

GET http://localhost:3333/boneca?search=MATTEL

###
 
PUT http://localhost:3333/bonecas/4589bd40-5875-4128-8de6-55d4e37c5d63
Content-Type: application/json

{
    "colecao": "Boneca de Coleção de Patins",
    "marca": "Mattel",
    "descricao": "Ela usa um collant colorido com uma viseira rosa choque, shorts de ciclista combinando e patins inline Impala neon. Semelhante à Barbie interpretada no filme,"
}

###

DELETE http://localhost:3333/bonecas/4589bd40-5875-4128-8de6-55d4e37c5d63